Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -46,18 +46,24 @@ jobs:
       - name: Create a new discussion
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          CATEGORY_ID: "DIC_kwDONnjXbM4Cl2Qi"
+          CATEGORY_ID: "DIC_kwDONnjXbM4Cl942"
           TITLE: "Hello World"
           BODY: "Hello World"
         run: |
           repo_id="${{ steps.fetch-repo-id.outputs.repo_id }}"
-          curl -X POST \
+          
+          response=$(curl -X POST \
             -H "Authorization: Bearer $GITHUB_TOKEN" \
             -H "Content-Type: application/json" \
             -d "{
               \"query\": \"mutation { createDiscussion(input: { repositoryId: \\\"$repo_id\\\", title: \\\"$TITLE\\\", body: \\\"$BODY\\\", categoryId: \\\"$CATEGORY_ID\\\" }) { discussion { id title url } } }\"
             }" \
-            https://api.github.com/graphql
-
+            https://api.github.com/graphql)
+            
+          if echo "$response" | grep -q '"errors"'; then
+            echo "Error: Failed to create discussion. Invalid CATEGORY_ID."
+            exit 1
+          fi
+          echo "Discussion created successfully."
 
 
